<?php
    $lan = array(
        //accueil
        'menu'=>'导航栏',
        'menu_index'=>'首页',
        'menu_presentation'=>'公司介绍',
        'menu_product'=>'产品',
        'menu_qrshop'=>'QRSHOP',
        'menu_customer'=>'客户',
        'menu_contact'=>'联系我们',
        'menu_budget'=>'价格预估',
                 
        'ad_cashier'=>'Weshop收银系统帮您',
        'ad_cashier_1'=>'提高效率',
        'ad_cashier_2'=>'增加客流量',
        'ad_cashier_3'=>'提升营业额',
        'ad_cashier_4'=>'您的经营好帮手！',
                 
        'button_budget'=>'价格预估',
        'button_product'=>'产品展示',
                 
        'banners_service'=>'聆听顾客需求，为您提供一应俱全的服务',
                 
        'why_chose_us'=>'选择Weshop',
        'why_chose_us_1'=>'致力于收银系统的专家',
        'our_software'=>'我们的软件',
                 'our_software_1'=>'作为政府认证的收银软件，严格符合法规政策，具有政府证书认证。操作简单，功能齐全，零门槛，让您轻松管理您的店铺。',
        'our_equipment'=>'我们的设备',
        'our_equipment_1'=>'Weshop收银系统可用于传统收银机、智能手机、平板电脑等多种设备，并且支持Windows和安卓两大操作系统。在合理的预算内，给您提供充足的选择。',
        'our_service'=>'我们的服务',
        'our_service_1'=>'Weshop每周六天为您提供多语言咨询和售后服务(法语、中文、英语、韩语)。微信客服，电话热线在线为您提供帮助，解决问题。',
                 
        'banners_agency'=>'办公地点',
        'banners_shop'=>'合作店铺',
        'banners_experience'=>'行业经验',
        'banners_user'=>'累计用户',
                 
        'equipment_exhibition'=>'设备',
        'equipment_exhibition_1'=>'我们为您提供最好的收银机',
        'equipment_cashier'=>'平板收银机',
        'equipment_pad'=>'台式收银机',
        'equipment_phone'=>'点单手机',
                 
        'budget_online'=>'在线价格预估',
        'budget_online_1'=>'免费获得您的软件和设备报价',
        'main_product'=>'主要产品',
        'main_product_cashier'=>'台式收银机和软件',
        'main_product_pad'=>'平板收银机和软件',
        'main_product_software'=>'软件',
        'other_product'=>'其他产品',
        'other_product_phone'=>'手机',
        'other_product_printer'=>'打印机',
        'other_product_cashbox'=>'钱箱',
        'other_product_scales'=>'电子秤',
        'other_product_scanner'=>'扫描仪',
        'other_product_guestscreen'=>'客显',
        'other_product_advice'=>'需要建议',
        'budget_info'=>'您的信息',
        'budget_info_company'=>'公司名 *',
        'budget_info_email'=>'邮箱 *',
        'budget_info_phone'=>'电话 *',
        'budget_info_postcode'=>'邮编',
        'budget_info_address'=>'地址',
        'budget_info_message'=>'留言',
        'budget_info_submit'=>'提交',
                 
        //présentation
        'about_weshop'=>'关于Weshop',
        'presentation_company'=>'公司',
    'presentation_company_1'=>'Weshop收银软件公司，总部位于法国巴黎。自2015年创办以来，致力于收银软件及设备的研发，为顾客提供相关的解决方案，打造现代化店铺管理模式。收银系统整合了商业大数据和智能设备，带给商家及消费者便利，来塑造科技零售美好生活。',
        'presentation_company_2'=>'作为法国政府认证的首家华人收银软件公司，Weshop在工作领域有良好的信誉。目前为止，我们在全法范围内已拥有数以千计的用户。',
        'presentation_task'=>'任务',
    'presentation_task_1'=>'我们可根据您的预算和店铺规模，为您量身定做购买方案。除此之外，我们的服务还涵盖：设备的安装与配置，软件使用培训，远程或实地维修，微信和电话热线售后等。',
        'presentation_task_2'=>'将为顾客服务作为我们的工作宗旨，Weshop提供6x10小时的客服服务，为您答疑解忧。您的满意是我们工作最大的动力。',
        'presentation_aims'=>'目标',
        'presentation_aims_1'=>'对企业：不断创新，增强行业竞争力。引领行业进步，传递现代理念与文化力量。',
        'presentation_aims_2'=>'对客户：聆听顾客需求，帮助客户将管理、技术、执行融合到IT系统中，为客户打造现代商业与管理模式。',
    'presentation_aims_3'=>'对员工：打造一个宽松严谨的学习与工作平台，让员工在此获得现代知识与受用一生的做人与做事的方法与准则。创建一个相互支撑又平等竞争的环境与氛围，让员工在此谋求发展并实现人生梦想。',
                 
        //produit
        'product'=>'我们的产品',
        'product_cashier'=>'传统收银机',
    'product_cashier_1'=>'Weshop为您提供全套的收银设备及软件，适用于餐厅、超市、甜品店、奶茶店、零售及批发商等。根据您的需求，您可以从收银机、钱箱、打印机、客显中进行选购。实用的功能使您倍感便捷，管理顾客订单，选择支付方式，浏览日、月账单，开具发票等功能一应俱全。',
        'product_cashier_2'=>'一台触屏式收银机，足以让你轻松管理您的店铺。',
        'product_pad'=>'平板收银机',
    'product_pad_1'=>'Weshop为您提供便携的平板电脑收银机，适用于餐厅、糕点店、超市、烟草店及酒吧等。您可以选择购买我们的平板及软件，或在您的设备上租赁我们的收银软件。耐用，轻便，性能卓越，并且具有传统收银机的所有功能。实惠的价格，更可以帮您节省预算。',
        'product_pad_2'=>'您可以随时安全地查看您的数据。平板收银机将与您的服务器实时连接，避免数据丢失。',
        'product_phone'=>'点单手机',
    'product_phone_1'=>'Weshop推出了可以连接收银系统的点单手机。您可以使用手机作为点单工具，即时记录顾客需求。使用点单手机帮助您节约时间与成本，从而提高您的利润。配合Weshop收银系统一起使用，将大大提高您的工作效率。',
                 
        //QRshop
        'about_qrshop'=>'关于QRshop',
        'qrshop_intro_1'=>'QRshop是Weshop公司独立开发的基于移动互联网时代餐饮智慧化管理与解决方案。',
    'qrshop_intro_2'=>'QRshop—云智慧餐厅管理系统，通过兼容传统餐饮设备和互联网优势，帮助商家完成互联网转型升级，同时给出互联网餐厅解决方案：包括预定、外卖、堂食、打包、会员卡、优惠券等多种业务内容。全面改造餐厅经营业务的每一个细节流程，多维度为餐厅增加移动互联网属性。',
        'qrshop_instruction'=>'使用介绍',
        'qrshop_download'=>'1. 下载',
        'qrshop_download_1'=>'从Apple Store、Google Play等应用商店下载',
        'qrshop_registered'=>'2. 注册',
        'qrshop_registered_1'=>'使用手机号注册账号、开创商铺',
        'qrshop_scan'=>'3. 扫码',
        'qrshop_scan_1'=>'客人通过扫描桌面二维码直接下单',
        'qrshop_orders'=>'4. 接单',
        'qrshop_orders_1'=>'商家通过手机确认接单，小票机出单',
        'qrshop_preparation'=>'5. 备餐',
        'qrshop_preparation_1'=>'厨师开始备餐',
        'qrshop_takemeal'=>'6. 取餐',
        'qrshop_takemeal_1'=>'客人取餐、堂食或外送',
        'qrshop_advantage'=>'QRshop如何给您带来效益',
        'qrshop_advantage_1'=>'用QRshop点单，简单高效！',
        'qrshop_advantage_beneficial'=>'提高收益',
        'qrshop_advantage_beneficial_1'=>'无接触点单，代替传统点单模式，节省纸质菜单成本',
        'qrshop_advantage_beneficial_2'=>'根据目前使用商家数据反馈，在节省成本的同时提高营业额10%-20%',
        'qrshop_advantage_quike'=>'快捷高效',
        'qrshop_advantage_quike_1'=>'优化工作流程，提高工作效率',
        'qrshop_advantage_quike_2'=>'扫码下单，提高翻台率，下单时间比传统点单平均减少30%',
        'qrshop_advantage_attractive'=>'吸引顾客',
        'qrshop_advantage_attractive_1'=>'智能客户管理系统，商家直接获取客户信息',
        'qrshop_advantage_attractive_2'=>'支持会员卡和会员积分，帮您抓住新顾客，留住老顾客',
                 
        //nos clients
        'our_customer'=>'我们的客户',
        'customer_evaluation'=>'客户评价',
        'customer_evaluation_1'=>'您的满意是我们最大的动力',
                 
        //contact
        'contact_weshop'=>'联系Weshop',
        'contact_us'=>'联系方式',
        'contact_address'=>'地址',
        'contact_phone'=>'电话',
        'contact_email'=>'邮箱',
        'contact_web'=>'官网',
                 
                 
        //footer
    'footer_weshop'=>'Weshop是法国政府认证的华人第一家收银软件供应商。作为收银软件开发的先驱，为您提供完整的收银系统解决方案。我们提供产品展示、咨询顾问、操作培训、远程维修等多种服务方式，为您创造最好的用户体验。',
        'footer_article'=>'最新推文',
        'footer_contact'=>'联系方式',
        'footer_right'=>'Tous droits réservés | Weshop收银软件公司版权所有',
        'chat_history'=>'以上是历史消息',
        'chat_popup'=>'您好，您需要帮助吗？',
        'chat_msg_default'=>'您好，欢迎您浏览我们的网页',
        
    );
    // $data = json_encode($lang);
    // echo $data;
?>
