<?php
    $lan = array(
        //accueil
        'menu'=>'MENU',
        'menu_index'=>'Accueil',
        'menu_presentation'=>'Présentation',
        'menu_product'=>'Produits',
        'menu_qrshop'=>'QRSHOP',
        'menu_customer'=>'Nos Clients',
        'menu_contact'=>'Contact',
        'menu_budget'=>'DEVIS',
                 
        'ad_cashier'=>'La caisse enregistreuse',
        'ad_cashier_1'=>'facilite votre vie',
        'ad_cashier_2'=>'économise votre temps',
        'ad_cashier_3'=>'augmente vos CA',
        'ad_cashier_4'=>'Votre meilleur assistant de gestion !',
                 
        'button_budget'=>'DEMANDER UN DEVIS',
        'button_product'=>'Nos Produits',
                 
        'banners_service'=>'Nous fournissons un excellent service',
                 
        'why_chose_us'=>'Pourquoi nous choisir',
        'why_chose_us_1'=>'Experts en logiciel de caisse enregistreuse',
        'our_software'=>'Notre logiciel',
                 'our_software_1'=>'Logiciel légal & fiable & pratique. Il conforme à la loi des finances 2016 et au certifiée NF525, obligatoire à partir du 1er janvier 2018.',
        'our_equipment'=>'Notre équipement',
        'our_equipment_1'=>'Peut être utilisé sur les caisses, les téléphones mobiles, les tablettes et autres appareils. Prise en charge des systèmes Windows et Linux.',
        'our_service'=>'Notre service',
        'our_service_1'=>'À votre service 6 jours par semaine. Nous mettons à votre disposition un service après-vente multilingue en français, anglais, chinois et coréen.',
                 
        'banners_agency'=>'agences',
        'banners_shop'=>'collaborateurs',
        'banners_experience'=>'ans d’expérience',
        'banners_user'=>'clients en France',
                 
        'equipment_exhibition'=>'LE MATÉRIEL',
        'equipment_exhibition_1'=>'Chez Weshop, nous vous fournissons les meilleurs caisses',
        'equipment_cashier'=>'Tablette',
        'equipment_pad'=>'Caisse traditionnelle',
        'equipment_phone'=>'Télécommande portable',
                 
        'budget_online'=>'DEVIS CAISSE ENREGISTREUSE EN LIGNE',
        'budget_online_1'=>'Recevez votre devis en logiciel et matériel de caisse gratuitement',
        'main_product'=>'Principaux produits',
        'main_product_cashier'=>'Caisse et logiciel',
        'main_product_pad'=>'Tablette et logiciel',
        'main_product_software'=>'Logiciel',
        'other_product'=>'Autres produits',
        'other_product_phone'=>'Smartphone',
        'other_product_printer'=>'Imprimante',
        'other_product_cashbox'=>'Tiroir',
        'other_product_scales'=>'Balance',
        'other_product_scanner'=>'Scanneur',
        'other_product_guestscreen'=>'Ecran de client',
        'other_product_advice'=>'Conseillez-moi',
        'budget_info'=>'Vos Informations',
        'budget_info_company'=>'Nom&nbsp;de&nbsp;la&nbsp;société&nbsp;&#42;',
        'budget_info_email'=>'Mail&nbsp;&#42;',
        'budget_info_phone'=>'Tél&nbsp;&#42;',
        'budget_info_postcode'=>'Code&nbsp;postal',
        'budget_info_address'=>'Adresse',
        'budget_info_message'=>'Votre&nbsp;message',
        'budget_info_submit'=>'OBTENIR&nbsp;LE&nbsp;DEVIS',
                 
        //présentation
        'about_weshop'=>'A Propos De Weshop',
        'presentation_company'=>'Notre Société',
    'presentation_company_1'=>'Weshop, crée en 2015, est une entreprise spécialisée dans le conseil en systèmes et le développement de logiciels informatiques pour les caisses enregistreuses. Aussi évolué qu’une caisse enregistreuse tactile, notre logiciel vous permet de simplifier la gestion de vos ventes et de vos produits tout en ayant un meilleur contrôle sur votre commerce.',
        'presentation_company_2'=>'Weshop jouit d&#39;une bonne réputation et compte jusqu&#39;à présent des milliers de clients en France.',
        'presentation_task'=>'Nos Missions',
    'presentation_task_1'=>'Chez Weshop, nous vous fournissons des conseils d&#39;achat en fonction de votre budget. La société propose également à ses clients des solutions personnalisées et met à disposition divers services : installation et configuration des équipements, formation d&#39;utilisation, maintenance à distance ou sur place, service après-vente et contact de différentes hotlines.',
        'presentation_task_2'=>'Nous sommes prêts à vous servir à tout moment.',
        'presentation_aims'=>'Nos Objectifs',
        'presentation_aims_1'=>'Nous intervenons dans le but de partager notre savoir-faire et d’assurer une complète autonomie à nos clients. Écouter les besoins de nos clients afin de garantir des produits qui soient en adéquation avec ces derniers.',
        'presentation_aims_2'=>'Notre entreprise tend vers l&#39;innovation constante afin de consolider ses acquis et de développer notre compétitivité dans le secteur.',
    'presentation_aims_3'=>'',
                 
        //produit
        'product'=>'Nos Produits De Caisse',
        'product_cashier'=>'Caisse traditionnelle',
    'product_cashier_1'=>'Weshop Caisse vous offre un ensemble d’équipement et un logiciel d’encaissement adapté aux restaurants, salons de thé, supermarchés, détaillants et grossistes etc. Suivant vos besoins, vous pouvez acheter une caisse enregistreuse, un tiroir métallique, une imprimante et un afficheur client. Autant évolué qu’une caisse enregistreuse tactile, notre logiciel vous permet de simplifier la gestion de vos ventes et de vos produits tout en ayant un meilleur contrôle sur votre commerce. Vous y trouverez des fonctionnalités très pratiques telles que la gestion des stocks et des commandes clients, la gestion des moyens de paiements et de vos statistiques, l’impression et la séparation des commandes selon les produits commandés, etc…',
        'product_cashier_2'=>'',
        'product_pad'=>'Tablette',
    'product_pad_1'=>'Weshop vous offre la tablette d’encaissement idéale pour les restaurants, salons de thé, cafés et bars etc. Vous pouvez choisir soit d&#39;acheter notre tablette, soit de choisir d&#39;utiliser votre propre appareil et de louer uniquement notre logiciel. Durable, Ultralégère, puissance et performance exceptionnelles. Petit et exquis, il a également toutes les fonctions d&#39;une caisse enregistreuse traditionnelle. Un prix abordable, choisir une tablette peut vous aider à économiser votre budget. La tablette sera connectée avec votre serveur en temps réel. Cela vous permettra de récupérer vos données intégralement et en toute sécurité.',
        'product_pad_2'=>'',
        'product_phone'=>'Télécommande portable',
    'product_phone_1'=>'Weshop lance des téléphones portables qui peuvent être connectés au système de caisse enregistreuse. Vous pouvez utiliser votre smartphone comme terminal de prise de commande pour saisir les commandes des clients de votre restaurant directement en salle. Cela vous aidera à économiser le temps et les coûts de commande et donc à améliorer vos profits. C&#39;est utilisable en collaboration avec notre logiciel d’encaissement.',
                 
        //QRshop
        'about_qrshop'=>'QRshop',
        'qrshop_intro_1'=>'QRshop est une application pour smartphone développée indépendamment par WeShop, qui permet aux clients de passer leur commande en scannant le QR code des restaurants. Cette application vous offre une solution intégrée de gestion intelligente de vos établissements.',
    'qrshop_intro_2'=>'Avec QRshop, vos clients ont plusieurs possibilités: commander leur plat à emporter, en livraison ou réserver pour dîner. Vous pouvez également gérer les informations des clients grâce au système de gestion de fidélité et leur envoyer des informations de promotion.',
        'qrshop_instruction'=>'Instructions',
        'qrshop_download'=>'1. Téléchargement',
        'qrshop_download_1'=>'Téléchargez l’application depuis Apple Store, Google Play ou Huawei AppGallery',
        'qrshop_registered'=>'2. Inscription',
        'qrshop_registered_1'=>'Gérez votre boutique avec votre numéro de téléphone portable',
        'qrshop_scan'=>'3. Scannage',
        'qrshop_scan_1'=>'Les clients scannent votre QR code pour regarder le menu et faire la commande',
        'qrshop_orders'=>'4. Validation',
        'qrshop_orders_1'=>'Validez la commande et votre imprimante sort automatiquement les tickets',
        'qrshop_preparation'=>'5. Préparation',
        'qrshop_preparation_1'=>'Le chef commence à préparer leur commande',
        'qrshop_takemeal'=>'6. Récupération',
        'qrshop_takemeal_1'=>'Les clients récupèrent leur commande au comptoir sans attendre ou mangent sur place',
        'qrshop_advantage'=>'Les avantages de QRshop',
        'qrshop_advantage_1'=>'Commander avec QRshop. C’est facile !',
        'qrshop_advantage_beneficial'=>'Profitable',
        'qrshop_advantage_beneficial_1'=>'Selon la situation actuelle, une augmentation du chiffre d&#39;affaires de 10-20%.',
        'qrshop_advantage_beneficial_2'=>'',
        'qrshop_advantage_quike'=>'Effectif',
        'qrshop_advantage_quike_1'=>'Vos commandes seront passées jusqu&#39;à 30% plus vite. La gestion de votre base de données clients sera plus facile.',
        'qrshop_advantage_quike_2'=>'',
        'qrshop_advantage_attractive'=>'Attractif',
        'qrshop_advantage_attractive_1'=>'Ce système intelligent de gestion client s’accompagne d’une carte de fidélité pour vous aider à fidéliser votre clientèle en plus d’attirer de nouveaux clients.',
        'qrshop_advantage_attractive_2'=>'',
                 
        //nos clients
        'our_customer'=>'Nos Clients',
        'customer_evaluation'=>'Les témoignages',
        'customer_evaluation_1'=>'Nos clients sont satisfaits',
                 
        //contact
        'contact_weshop'=>'CONTACTEZ WESHOP',
        'contact_us'=>'Nous contacter',
        'contact_address'=>'Adresse',
        'contact_phone'=>'Tél',
        'contact_email'=>'Mail',
        'contact_web'=>'Site web',
                 
                 
        //footer
    'footer_weshop'=>'Weshop est un fournisseur de caisses enregistreuses tactiles. Il met à votre disposition des équipements et des logiciels de caisse complets, ainsi que des équipements de réseau (routeur, téléphone portable).',
        'footer_article'=>'Dernières nouvelles',
        'footer_contact'=>'Nous contacter',
        'footer_right'=>'Tous droits réservés | Pour plus d’informations voir SARL WESHOP',
        'chat_history'=>'Msgs historiques dessus',
        'chat_popup'=>'Bonjour, je peux vous aider ?',
        'chat_msg_default'=>'Bonjour, bienvenue chez WeShop !',
        
    );
    // $data = json_encode($lang);
    // echo $data;
?>
